### ISSUE TITLE
Laggy UI on Mibox/Samsung devices

### ISSUE THREAD

**Issue by TVZionDev** [TVZionDev/TVZionAndroidApp#7]

**Comment by TVZionDev** [comment]
1.17.BETA.2 update should fix this.

**Comment by palradu** [comment]
This still happens on the MiBox even on v3.0, but only on the Oreo build. It works great on the old Marshmallow build. If you need a MiBox tester for the app, I'd be happy to help test/debug. Just let me know. My MiBox is updated to the latest 8.0 build.
